# Generated by Django 5.0.7 on 2024-11-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_userprofile_four_digit_auth_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
