# Generated by Django 5.0.7 on 2024-11-25 00:16

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_userprofile_card_number_userprofile_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='card_number',
            field=models.CharField(default=bank_app.models.generate_card_number, max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cvv',
            field=models.CharField(default=bank_app.models.generate_cvv, max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiry_month',
            field=models.CharField(default=bank_app.models.generate_expiry_date, max_length=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiry_year',
            field=models.CharField(default=bank_app.models.generate_expiry_date, max_length=4),
        ),
    ]
