# Generated by Django 5.0.7 on 2024-11-25 00:23

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_userprofile_card_number_alter_userprofile_cvv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='expiry_month',
            field=models.CharField(default=bank_app.models.generate_expiry_date, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='expiry_year',
            field=models.CharField(default=bank_app.models.generate_expiry_date, max_length=15),
        ),
    ]
