# Generated by Django 5.0.7 on 2024-11-25 00:39

import bank_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_userprofile_expiry_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='expiry_month',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expiry_year',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expiry_date',
            field=models.CharField(default=bank_app.models.generate_expiry_date, max_length=7),
        ),
    ]
